# Generated by Django 2.0.3 on 2018-03-22 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMSTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(choices=[(100, 'Phone number verification'), (200, 'Forgot username/email')], db_index=True, help_text='SMS type.', unique=True, verbose_name='Key')),
                ('body', models.CharField(db_index=True, help_text='SMS body.', max_length=255, verbose_name='body')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Template creation date.', verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Template update date.', verbose_name='Updated at')),
                ('is_active', models.BooleanField(default=True, help_text='Is template active.', verbose_name='Active')),
            ],
            options={
                'verbose_name': 'SMS template',
                'verbose_name_plural': 'SMS templates',
            },
        ),
    ]
