# Generated by Django 2.0.3 on 2018-03-19 17:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Phone number.', max_length=16, validators=[django.core.validators.RegexValidator('^\\+\\d{9,15}$')], verbose_name='Phone number')),
                ('is_verified', models.BooleanField(default=False, help_text='Is phone verified.', verbose_name='Verified')),
            ],
            options={
                'verbose_name': 'Phone number',
                'verbose_name_plural': 'Phone numbers',
            },
        ),
    ]
