# Generated by Django 2.0.3 on 2018-03-22 13:26

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(blank=True, help_text='Street.', max_length=100, null=True, verbose_name='Street')),
                ('city', models.CharField(blank=True, help_text='City.', max_length=100, null=True, verbose_name='City')),
                ('state', models.CharField(blank=True, help_text='State.', max_length=2, null=True, verbose_name='State')),
                ('country', django_countries.fields.CountryField(blank=True, db_index=True, default='', max_length=746, multiple=True)),
                ('point', django.contrib.gis.db.models.fields.PointField(geography=True, null=True, srid=4326)),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
        migrations.CreateModel(
            name='Zipcode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Zipcode.', max_length=5, verbose_name='Zipcode')),
                ('poly', django.contrib.gis.db.models.fields.PolygonField(help_text='Poly.', srid=4326, verbose_name='Poly')),
            ],
            options={
                'verbose_name': 'Zipcode',
                'verbose_name_plural': 'Zipcodes',
            },
        ),
    ]
