# Generated by Django 2.0.3 on 2018-03-19 17:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='user',
            field=models.ForeignKey(help_text='A user who have this location.', on_delete=django.db.models.deletion.CASCADE, related_name='locations', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='location',
            name='zipcode',
            field=models.ForeignKey(blank=True, help_text='Zipcode.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='location.Zipcode', verbose_name='Zipcode'),
        ),
    ]
