# Generated by Django 2.0.3 on 2018-03-23 15:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='UUID Primary key')),
                ('staff_only', models.BooleanField(default=False, help_text='This room can be available only for staff users.', verbose_name='Staff only')),
            ],
        ),
    ]
